version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: final-project
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INIT_DB_ARGS: --encoding=UTF-8
